const ProjectsData = [
  {
    id: 1,
    title: 'NextJS Portfolio Website',
    image: '/project-images/port.png',
    tag: ['All', 'Personal'],
    gitUrl: '/',
    previewUrl: '/',
  },
  {
    id: 2,
    title: 'Crowd Funding landing page',
    image: '/project-images/crowd.png',
    tag: ['All', 'Challenges'],
    gitUrl: '/',
    previewUrl: '/',
  },
  {
    id: 3,
    title: 'Landing Page',
    image: '/project-images/new.png',
    tag: ['All', 'Personal'],
    gitUrl: 'https://github.com/binisha9AA/landing-page',
    previewUrl: '/',
  },
  {
    id: 4,
    title: 'Meme Generator',
    image: '/project-images/meme.png',
    tag: ['All', 'Challenges'],
    gitUrl: 'https://github.com/binisha9AA/meme-generator',
    previewUrl: '/',
  },
  {
    id: 5,
    title: 'JR Safety',
    image: '/project-images/jr.png',
    tag: ['All', 'Projects'],
    gitUrl: '/',
    previewUrl: '/',
  },
  {
    id: 6,
    title: 'SWI Fencing',
    image: '/project-images/swi.png',
    tag: ['All', 'Projects'],
    gitUrl: '/',
    previewUrl: '/',
  },
  {
    id: 7,
    title: 'Cigweld',
    image: '/project-images/combiner.png',
    tag: ['All', 'Projects'],
    gitUrl: '/',
    previewUrl: '/',
  },
  {
    id: 8,
    title: 'Weldlock',
    image: '/project-images/weld.png',
    tag: ['All', 'Projects'],
    gitUrl: '/',
    previewUrl: '/',
  },
  {
    id: 8,
    title: 'Todos List',
    image: '/project-images/todo.png',
    tag: ['All', 'Personal'],
    gitUrl: '/',
    previewUrl: '/',
  },
  {
    id: 9,
    title: 'News Landing Page',
    image: '/project-images/news.png',
    tag: ['All', 'Challenges'],
    gitUrl: 'https://github.com/binisha9AA/news-homepage',
    previewUrl: '/',
  },
  {
    id: 10,
    title: 'URL Shortening API',
    image: '/project-images/url.png',
    tag: ['All', 'Challenges'],
    gitUrl: 'https://github.com/binisha9AA/url-shortening-api',
    previewUrl: '/',
  },
  {
    id: 11,
    title: 'Intro UI',
    image: '/project-images/intro.png',
    tag: ['All', 'Challenges'],
    gitUrl: 'https://github.com/binisha9AA/intro_page',
    previewUrl: '/',
  },
];

export default ProjectsData;
